// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package model

// ReqRecord defines model for Req-record.
type ReqRecord struct {
	Datetime *string `json:"datetime,omitempty"`
	From     *string `json:"from,omitempty"`
	Memo     *string `json:"memo,omitempty"`
	Price    *int    `json:"price,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// ResRecord defines model for Res-record.
type ResRecord struct {
	CategoryId   *int     `json:"category_id,omitempty"`
	CategoryName *string  `json:"category_name,omitempty"`
	Date         *string  `json:"date,omitempty"`
	From         *string  `json:"from,omitempty"`
	Id           *float32 `json:"id,omitempty"`
	Memo         *string  `json:"memo,omitempty"`
	Price        *int     `json:"price,omitempty"`
	Type         *string  `json:"type,omitempty"`
}

// CategoryYearSummary defines model for category_year_summary.
type CategoryYearSummary struct {
	CategoryId   *float32   `json:"category_id,omitempty"`
	CategoryName *string    `json:"category_name,omitempty"`
	Price        *[]float32 `json:"price,omitempty"`
	Total        *float32   `json:"total,omitempty"`
}

// PostRecordJSONRequestBody defines body for PostRecord for application/json ContentType.
type PostRecordJSONRequestBody = ReqRecord
