version: '3'

services:
  mawinter-db:
    image: mariadb:10.9
    container_name: mawinter-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mawinter
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
  mawinter-api:
    image: mawinter-api:latest
    container_name: mawinter-api
    ports:
      - "8080:8080"
    environment:
      - BASIC_AUTH_USERNAME=user
      - BASIC_AUTH_PASSWORD=pass
  # mawinter-register:
  #   image: mawinter-register:latest
  #   container_name: mawinter-register
  #   ports:
  #     - "8080:8080"
  #   command:
  #   - bill-host
  #   - localhost
  #   - bill-port
  #   - "8080"
