version: '3'

services:
  mawinter-db:
    image: mariadb:10.9
    container_name: mawinter-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mawinter
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
  mawinter-api:
    image: mawinter-api:latest
    container_name: mawinter-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mawinter-db
      - DB_PORT=3306
      - DB_NAME=mawinter
      - DB_USER=root
      - DB_PASS=password

  # mawinter-register:
  #   image: mawinter-register:latest
  #   container_name: mawinter-register
  #   command:
  #   - "fixmonth"
  #   environment:
  #     - MAIL_HOST=smtp.gmail.com
  #     - MAIL_PORT=587
  #     - MAIL_USER=x
  #     - MAIL_PASS=x
  #     - MAIL_TO=x

