version: "3"

services:
  db:
    image: mariadb:10.7.3
    restart: always
    container_name: mawinter-db
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mawinter-test
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
    volumes:
      - ../build/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  maw-api:
    build:
      context: ../
      dockerfile: build/Dockerfile
    container_name: mawinter-api
    ports:
      - "8080:80"
    environment:
      - BASIC_AUTH_USERNAME=test
      - BASIC_AUTH_PASSWORD=test
    command:
      - "--db-name"
      - "mawinter-test"
