openapi: 3.1.0
x-stoplight:
  id: iayxih3222x5z
info:
  title: mawinter-api
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:8080'
paths:
  /:
    get:
      summary: health check
      tags: []
      responses: {}
      operationId: get
      description: health check
  /v1/record:
    post:
      summary: post new a record
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Res-record'
              examples:
                Example 1:
                  value:
                    id: 123
                    category_id: 400
                    category_name: cat1
                    date: '2021-01-01T00:00:00Z'
                    from: discord
                    type: ''
                    price: 1234
                    memo: ''
      operationId: post-record
      description: 家計簿データを追加する。
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Req-record'
            examples:
              Example 1:
                value:
                  category_id: 120
                  datetime: '20210101'
                  from: discord
                  type: ''
                  price: 210
                  memo: ''
    parameters: []
  '/v1/record/year/{year}':
    parameters:
      - schema:
          type: string
        name: year
        in: path
        required: true
    get:
      summary: get year records
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category_year_summary'
              examples:
                Example 1:
                  value:
                    category_id: 0
                    category_name: string
                    price:
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                      - 300
                    total: 0
      operationId: get-record-year-year
      description: 'FY{year} の 年間サマリを取得する。'
  '/table/{year}':
    parameters:
      - schema:
          type: number
        name: year
        in: path
        required: true
    post:
      summary: create new YYYYMM table
      tags: []
      responses: {}
      operationId: post-table-year
      deprecated: true
components:
  schemas:
    category_year_summary:
      title: category_year_summary
      x-stoplight:
        id: 3cphpxfvazyb5
      type: object
      properties:
        category_id:
          type: number
        category_name:
          type: string
        price:
          type: array
          maxItems: 12
          minItems: 12
          items:
            type: number
            default: 0
            example: 300
        total:
          type: number
    Req-record:
      title: record_request
      x-stoplight:
        id: fnqupuq6bqa9u
      type: object
      properties:
        datetime:
          type: string
          example: '20060102'
          pattern: '[0-9]+'
        from:
          type: string
        type:
          type: string
        price:
          type: integer
        memo:
          type: string
    Res-record:
      title: record_response
      x-stoplight:
        id: o1vcp44w8basy
      type: object
      properties:
        id:
          type: number
        category_id:
          type: integer
        category_name:
          type: string
        date:
          type: string
          example: '2021-01-01T00:00:00Z'
        from:
          type: string
        type:
          type: string
        price:
          type: integer
        memo:
          type: string
  requestBodies: {}
