name: Build and Publish

on:
  push: # TODO
    tags:
      - v*

  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz
      - name: unzip pandoc
        run: tar -xzvf pandoc-2.18-linux-amd64.tar.gz
      - name: install pandoc
        run: sudo cp -a pandoc-2.18/bin/pandoc /usr/local/bin/

      - name: Build doc scripts
        run: make doc

      - name: Prepare docs-artifacts
        run: cd docs && tar -cvzf docs.tar.gz build && cd ..

      - uses: actions/upload-artifact@v3
        with:
          name: docs-artifacts
          path: docs/docs.tar.gz
          retention-days: 1

  build_sync:
    runs-on: ubuntu-latest
    needs: build_doc
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: docs-artifacts
          path: docs/docs.tar.gz

      - name: test print
        run: ls -la docs/docs.tar.gz
