name: Build and Publish Docs

on:
  push: # TODO
    tags:
      - v*

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz
      - name: unzip pandoc
        run: tar -xzvf pandoc-2.18-linux-amd64.tar.gz
      - name: install pandoc
        run: sudo cp -a pandoc-2.18/bin/pandoc /usr/local/bin/

      - name: Build doc scripts
        run: make doc

      - uses: actions/upload-artifact@v3
        with:
          name: docs-artifacts
          path: docs/build/
          retention-days: 1

  build_sync:
    runs-on: ubuntu-latest
    needs: build_doc
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: docs-artifacts
          path: docs/build/

      - name: Set Secret Key for Document Host
        run: echo "${SSH_KEY}" > id_for_sync && chmod 600 id_for_sync
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: rsync Build Documents
        run: rsync -avz -e "ssh -i id_for_sync -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ${DOC_FILES} ${REMOTE_HOST}:${CONTENTS_DIR}
        env:
          DOC_FILES: "./docs/build/*"
          REMOTE_HOST: "azuki@sage.azk774.net"
          CONTENTS_DIR: "/var/nginx/contents/mawinter/scheme/"
